### ISSUE TITLE
Usage without a Computer Box

### ISSUE THREAD

**Issue by fwarmuth** [takuya-ki/onrobot-vgc10#1]
Hey,
did you try to get this working using a UR10e, it provides a RS-485 interface.
I try to get things to work, but without much success...

Cheers

**Comment by takuya-ki** [comment]
@fwarmuth 
Since this package assumes a configuration of your computer - ethernet cable - compute box - tool changer - gripper, any UR-series arms are not included in the expected hardware configuration. Sorry the issue you're facing is not related to this repository.
